# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
baseurl:          /ps-contest-editorials

author:
  name:           'Mark Otto'
