# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            PS with ntopia
service_host:     https://ntopia.github.io
baseurl:          /ps-with-ntopia
repository:       ntopia/ps-with-ntopia