# Permalinks
permalink:           pretty

# Setup
title:               pstopia
description:         Notes for Problem Solving Contest
tagline:             Notes for Problem Solving Contest
baseurl:             /pstopia

defaults:
  -
    scope:
      path: "src"
    values:
      comments: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Gems
gems:
  - jekyll-gist
  - jekyll-seo-tag
